FROM ros:noetic-ros-base

# Install required tools and dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    vim \
    htop \
    git \
    libpcl-dev \
    #pcl-tools \
    ros-noetic-pcl-ros \
    ros-noetic-rviz \
    ros-noetic-hector-xacro-tools \
    ros-noetic-velodyne-description \
    ros-noetic-rqt-reconfigure \
    libgl1-mesa-glx \
    libglu1-mesa  

# Create catkin workspace/src folder
RUN mkdir -p /catkin_ws/src

# Add GitHub to known hosts to fix SSH host verification
RUN mkdir -p ~/.ssh && \
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

# Clone public repository into catkin_ws/src
RUN cd /catkin_ws/src && \
    /ros_entrypoint.sh git clone https://github.com/jkk-research/pointcloud_to_grid.git && \
    cd pointcloud_to_grid && \
    git checkout ros1

# Add a build argument to invalidate cache
ARG CACHEBUST=1

# Clone private repository using SSH into catkin_ws/src and checkout 'gruppe_2' branch
RUN --mount=type=ssh cd /catkin_ws/src && \
    /ros_entrypoint.sh git clone git@github.com:TW-Robotics/mre3-ear-lab-ws2024.git && \
    cd mre3-ear-lab-ws2024 && \
    git checkout gruppe_2

# Build the Catkin workspace
RUN cd /catkin_ws && \
    /ros_entrypoint.sh catkin_make

# Install ROS dependencies, skipping unresolved 'pcl'
RUN apt-get update && \
    rosdep update && \
    rosdep install --from-paths /catkin_ws/src -i -y --rosdistro noetic --skip-keys="pcl"

# Update the ROS entrypoint script to source the local workspace
RUN sed -i '$ d' /ros_entrypoint.sh && \
    echo "source /catkin_ws/devel/setup.bash" >> /ros_entrypoint.sh && \
    echo 'exec "$@"' >> /ros_entrypoint.sh

# Add sourcing commands to bashrc for interactive debugging
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc && \
    echo "source /catkin_ws/devel/setup.bash" >> ~/.bashrc

# Use Bash as the default shell
SHELL ["/bin/bash", "-c"]

# Set the ROS entrypoint
ENTRYPOINT ["/ros_entrypoint.sh"]

# Keep the container running with a lightweight process
CMD ["bash"]