version: "3.9"

services:
  ros-container:
    image: interface-docker
    container_name: interface_container
    network_mode: host  # Allows ROS to use the host network
    environment:
      - DISPLAY=${DISPLAY}  # Pass the host's DISPLAY variable for GUI
      - QT_X11_NO_MITSHM=1  # Fix shared memory issues for X11
      - QT_QPA_PLATFORM=xcb  # Ensures Qt applications use X11
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Share X11 socket for GUI applications
    stdin_open: true  # Keep STDIN open for interaction
    tty: true         # Allocate a pseudo-TTY for terminal access
    command: >
      bash -c "source /opt/ros/noetic/setup.bash &&
               source /catkin_ws/devel/setup.bash &&
               roslaunch interface_pkg interface.launch"
    restart: no
