FROM ros:noetic-ros-base

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends ros-noetic-move-base-flex ros-noetic-move-base

SHELL ["/bin/bash", "-c"]