FROM ros:noetic-ros-base

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    ros-noetic-actionlib-msgs ros-noetic-geometry-msgs \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app