arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
  gains:
    arm_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
  constraints:
    goal_time: &goal_time_constraint 5.0
    stopped_velocity_tolerance: 1.0
    arm_joint_1:
      goal: 0.1
      trajectory: 0.1
    arm_joint_2:
      goal: 0.1
      trajectory: 0.1
    arm_joint_3:
      goal: 0.1
      trajectory: 0.1
    arm_joint_4:
      goal: 0.1
      trajectory: 0.1
  stop_trajectory_duration: 1.0
